pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Hyprland config editor state — mirrors Config.qml's FileView+JsonAdapter
// persistence and ThemeHyprland.qml's buildX/writeX-then-reload convention,
// generalized across every helios/*.lua section this settings page manages.
QtObject {
    id: root

    readonly property var sectionNames: ["general", "decoration", "animations",
        "input", "group", "misc", "xwayland", "cursor", "render", "debug", "ecosystem"]

    function sectionState(name) {
        return draftAdapter.sections[name] || {};
    }

    function hasSaved(name) {
        const s = draftAdapter.sections[name];
        return !!s && Object.keys(s).length > 0;
    }

    function setSectionField(name, path, value) {
        const sections = draftAdapter.sections;
        if (!sections[name]) sections[name] = {};
        sections[name][path] = value;
        draftAdapter.sections = sections;
    }

    property FileView draftFile: FileView {
        path: Quickshell.statePath("hyprland-settings-draft.json")
        watchChanges: true

        JsonAdapter {
            id: draftAdapter
            // Keyed by section name -> flat {"decoration:rounding": 20, ...}.
            // Empty/missing section means "not yet saved, seed from hyprctl".
            property var sections: ({})
        }
    }

    function luaValue(v) {
        if (typeof v === "boolean" || typeof v === "number") return String(v);
        if (Array.isArray(v) && v.length === 2) return "{ " + v[0] + ", " + v[1] + " }";
        // String — escape backslash and double-quote, Hyprland regexes in
        // window/layer rules rely on this being a plain Lua double-quoted
        // string, not a long-bracket literal.
        return "\"" + String(v).replace(/\\/g, "\\\\").replace(/"/g, "\\\"") + "\"";
    }

    // Nests a flat {"a:b:c": v} object into hl.config({ top = { a = { b = { c = v } } } } }).
    function luaConfigBlock(topKey, flatState) {
        const tree = {};
        for (const path of Object.keys(flatState)) {
            const parts = path.split(":");
            let node = tree;
            for (let i = 0; i < parts.length - 1; i++) {
                node[parts[i]] = node[parts[i]] || {};
                node = node[parts[i]];
            }
            node[parts[parts.length - 1]] = flatState[path];
        }

        function renderTable(obj, indent) {
            const pad = "    ".repeat(indent);
            const innerPad = "    ".repeat(indent + 1);
            let out = "{\n";
            for (const key of Object.keys(obj)) {
                const v = obj[key];
                const rendered = (v !== null && typeof v === "object" && !Array.isArray(v))
                    ? renderTable(v, indent + 1)
                    : root.luaValue(v);
                out += innerPad + key + " = " + rendered + ",\n";
            }
            return out + pad + "}";
        }

        return "hl.config({\n    " + topKey + " = " + renderTable(tree[topKey] || {}, 1) + ",\n})\n";
    }

    function readLiveOptions(paths, onComplete) {
        const result = {};
        let i = 0;

        function next() {
            if (i >= paths.length) { onComplete(result); return; }
            const path = paths[i++];
            getOptionProc.command = ["hyprctl", "-j", "getoption", path];
            getOptionProc.__path = path;
            getOptionProc.running = false;
            getOptionProc.running = true;
        }

        getOptionProc.__onResult = (path, raw) => {
            try {
                const parsed = JSON.parse(raw);
                result[path] = "int" in parsed ? parsed.int
                    : "float" in parsed ? parsed.float
                    : "bool" in parsed ? parsed.bool
                    : "str" in parsed ? parsed.str
                    : "vec2" in parsed ? parsed.vec2
                    : null;
            } catch (e) {
                result[path] = null;
            }
            next();
        };

        next();
    }

    property Process getOptionProc: Process {
        property string __path: ""
        property var __onResult: null
        stdout: StdioCollector {
            onStreamFinished: getOptionProc.__onResult(getOptionProc.__path, text)
        }
    }

    readonly property var configErrors: _configErrors
    property var _configErrors: []

    function saveSection(name, luaBody) {
        const home = Quickshell.env("HOME");
        sectionFile.path = home + "/.config/hypr/helios/" + name + ".lua";
        sectionFile.setText("-- Generated by Helios — do not edit by hand\n\n" + luaBody);
        draftFile.writeAdapter();
        hyprctlReloadProc.running = false;
        hyprctlReloadProc.running = true;
    }

    property FileView sectionFile: FileView { printErrors: false; atomicWrites: true }

    property Process hyprctlReloadProc: Process {
        command: ["hyprctl", "reload"]
        onExited: root.checkConfigErrors()
    }

    function checkConfigErrors() {
        configErrorsProc.running = false;
        configErrorsProc.running = true;
    }

    property Process configErrorsProc: Process {
        command: ["hyprctl", "-j", "configerrors"]
        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    const parsed = JSON.parse(text);
                    root._configErrors = parsed.filter(e => e && e.length > 0);
                } catch (e) {
                    root._configErrors = [];
                }
            }
        }
    }
}
