pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Kitty
QtObject {
    id: root

    function buildKittyTheme(p) {
        return "# Generated by Helios (Themes.qml) — do not edit by hand\n\n"
            + "background " + p.background + "\n"
            + "foreground " + p.text + "\n"
            + "selection_background " + p.surfaceHigh + "\n"
            + "selection_foreground " + p.text + "\n"
            + "cursor " + p.accent + "\n"
            + "cursor_text_color " + p.background + "\n"
            + "url_color " + p.accent + "\n"
            + "active_border_color " + p.accent + "\n"
            + "inactive_border_color " + p.overlay + "\n"
            + "active_tab_foreground " + p.accentText + "\n"
            + "active_tab_background " + p.accent + "\n"
            + "inactive_tab_foreground " + p.subtext + "\n"
            + "inactive_tab_background " + p.surfaceHigh + "\n"
            + "tab_bar_background " + p.background + "\n"
            + "color0 " + p.surfaceHigh + "\n"
            + "color8 " + p.overlay + "\n"
            + "color1 " + p.danger + "\n"
            + "color9 " + p.danger + "\n"
            + "color2 " + p.success + "\n"
            + "color10 " + p.success + "\n"
            + "color3 " + p.warning + "\n"
            + "color11 " + p.warning + "\n"
            + "color4 " + p.accent + "\n"
            + "color12 " + p.accent + "\n"
            + "color5 " + p.accent + "\n"
            + "color13 " + p.accent + "\n"
            + "color6 " + p.accent + "\n"
            + "color14 " + p.accent + "\n"
            + "color7 " + p.text + "\n"
            + "color15 " + p.text + "\n";
    }

    function writeKittyTheme(p) {
        const home = Quickshell.env("HOME");
        kittyThemeFile.path = home + "/.config/kitty/themes/helios.conf";
        kittyThemeFile.setText(root.buildKittyTheme(p));

        kittyConfigFile.path = home + "/.config/kitty/kitty.conf";
        const existing = kittyConfigFile.text();
        const text = /^\s*include\s+themes\/helios\.conf\s*$/m.test(existing)
            ? existing
            : existing.replace(/\s*$/, "") + "\ninclude themes/helios.conf\n";
        kittyConfigFile.setText(text);

        // kitty reloads its config live on SIGUSR1 (remote-control-free
        // equivalent of `kitty @ load-config`) — harmless no-op if kitty
        // isn't running.
        kittySignalProc.running = false;
        kittySignalProc.running = true;
    }

    property FileView kittyThemeFile: FileView { printErrors: false; atomicWrites: true }
    property FileView kittyConfigFile: FileView { printErrors: false; atomicWrites: true; preload: true; blockLoading: true }
    property Process kittySignalProc: Process { command: ["pkill", "-USR1", "-x", "kitty"] }
}
