pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Rofi
QtObject {
    id: root

    function buildRofiTheme(p) {
        return "/* Generated by Helios (Themes.qml) — do not edit by hand */\n\n"
            + "* {\n"
            + "    background: " + p.background + ";\n"
            + "    background-alt: " + p.surface + ";\n"
            + "    foreground: " + p.text + ";\n"
            + "    foreground-alt: " + p.subtext + ";\n"
            + "    selected: " + p.accent + ";\n"
            + "    selected-text: " + p.accentText + ";\n"
            + "    active: " + p.success + ";\n"
            + "    urgent: " + p.danger + ";\n"
            + "    border-color: " + p.overlay + ";\n"
            + "}\n";
    }

    function writeRofiTheme(p) {
        const home = Quickshell.env("HOME");
        rofiThemeFile.path = home + "/.config/rofi/helios.rasi";
        rofiThemeFile.setText(root.buildRofiTheme(p));

        rofiConfigFile.path = home + "/.config/rofi/config.rasi";
        const existing = rofiConfigFile.text();
        const themeLine = "@theme \"helios\"";
        const text = /^\s*@theme\s+.*$/m.test(existing)
            ? existing.replace(/^\s*@theme\s+.*$/m, themeLine)
            : (existing || "").replace(/\s*$/, "") + "\n" + themeLine + "\n";
        rofiConfigFile.setText(text);
    }

    property FileView rofiThemeFile: FileView { printErrors: false; atomicWrites: true }
    property FileView rofiConfigFile: FileView { printErrors: false; atomicWrites: true; preload: true; blockLoading: true }
}
