pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Firefox
//
// Best-effort: only the default profile from a native (non-Flatpak)
// profiles.ini is handled. userChrome/userContent need
// toolkit.legacyUserProfileCustomizations.stylesheets enabled — done here
// via user.js, which (unlike prefs.js) is safe to hand-edit and takes
// effect on Firefox's next launch.
QtObject {
    id: root

    function findFirefoxProfile(iniText) {
        if (!iniText) return "";
        const blocks = iniText.split(/\n(?=\[)/);
        for (const b of blocks) {
            if (/^\[Install/.test(b)) {
                const m = b.match(/^Default=(.+)$/m);
                if (m) return m[1].trim();
            }
        }
        for (const b of blocks) {
            if (/^\[Profile/.test(b) && /^Default=1\s*$/m.test(b)) {
                const m = b.match(/^Path=(.+)$/m);
                if (m) return m[1].trim();
            }
        }
        return "";
    }

    function buildFirefoxCss(p) {
        return "/* Generated by Helios (Themes.qml) */\n"
            + ":root {\n"
            + "  --helios-bg: " + p.background + ";\n"
            + "  --helios-surface: " + p.surface + ";\n"
            + "  --helios-text: " + p.text + ";\n"
            + "  --helios-accent: " + p.accent + ";\n"
            + "}\n"
            + "#navigator-toolbox, #TabsToolbar, #nav-bar { background-color: var(--helios-surface) !important; }\n"
            + "#tabbrowser-tabs .tab-background[selected] { background-color: var(--helios-bg) !important; }\n"
            + ":root, .tab-label, #urlbar { color: var(--helios-text) !important; }\n"
            + "#urlbar-background { background-color: var(--helios-bg) !important; }\n";
    }

    function writeFirefoxTheme(p) {
        const home = Quickshell.env("HOME");
        firefoxIniFile.path = home + "/.mozilla/firefox/profiles.ini";
        const profile = root.findFirefoxProfile(firefoxIniFile.text());
        if (!profile) return; // No native profile found — skip silently.

        const profileDir = home + "/.mozilla/firefox/" + profile;

        firefoxUserJsFile.path = profileDir + "/user.js";
        const existingUserJs = firefoxUserJsFile.text();
        const pref = "toolkit.legacyUserProfileCustomizations.stylesheets";
        if (existingUserJs.indexOf(pref) < 0) {
            firefoxUserJsFile.setText((existingUserJs || "").replace(/\s*$/, "")
                + "\nuser_pref(\"" + pref + "\", true);\n");
        }

        root.pendingFirefoxCss = root.buildFirefoxCss(p);
        root.pendingFirefoxProfileDir = profileDir;
        firefoxMkdirProc.command = ["mkdir", "-p", profileDir + "/chrome"];
        firefoxMkdirProc.running = false;
        firefoxMkdirProc.running = true;
    }

    property string pendingFirefoxCss: ""
    property string pendingFirefoxProfileDir: ""

    property FileView firefoxIniFile: FileView { printErrors: false; preload: true; blockLoading: true }
    property FileView firefoxUserJsFile: FileView { printErrors: false; atomicWrites: true; preload: true; blockLoading: true }
    property FileView firefoxChromeFile: FileView { printErrors: false; atomicWrites: true }
    property FileView firefoxContentFile: FileView { printErrors: false; atomicWrites: true }
    property Process firefoxMkdirProc: Process {
        onExited: {
            if (!root.pendingFirefoxProfileDir) return;
            firefoxChromeFile.path = root.pendingFirefoxProfileDir + "/chrome/userChrome.css";
            firefoxChromeFile.setText(root.pendingFirefoxCss);
            firefoxContentFile.path = root.pendingFirefoxProfileDir + "/chrome/userContent.css";
            firefoxContentFile.setText(root.pendingFirefoxCss);
        }
    }
}
