pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Hyprland (border colors, via the hyprland-lua-config plugin)
QtObject {
    id: root

    function buildHyprlandTheme(p) {
        const active = root.hexToRgbColor(p.accent);
        const inactive = root.hexToRgbColor(p.surface);
        const locked = root.hexToRgbColor(p.danger);
        const textOnActive = root.hexToRgbColor(p.accentText);
        const textOnInactive = root.hexToRgbColor(p.text);
        return "-- Generated by Helios (Themes.qml) — do not edit by hand\n\n"
            + "local active = \"" + active + "\"\n"
            + "local inactive = \"" + inactive + "\"\n"
            + "local locked = \"" + locked + "\"\n"
            + "local text_active = \"" + textOnActive + "\"\n"
            + "local text_inactive = \"" + textOnInactive + "\"\n\n"
            + "local function apply_theme()\n"
            + "    hl.config({\n"
            + "        general = {\n"
            + "            col = {\n"
            + "                active_border = active,\n"
            + "                inactive_border = inactive,\n"
            + "            },\n"
            + "        },\n"
            + "        group = {\n"
            + "            col = {\n"
            + "                border_active = active,\n"
            + "                border_inactive = inactive,\n"
            + "                border_locked_active = locked,\n"
            + "                border_locked_inactive = inactive,\n"
            + "            },\n\n"
            + "            groupbar = {\n"
            + "                gradients = true,\n"
            + "                col = {\n"
            + "                    active = active,\n"
            + "                    inactive = inactive,\n"
            + "                    locked_active = locked,\n"
            + "                    locked_inactive = inactive,\n"
            + "                },\n"
            + "                text_color = text_active,\n"
            + "                text_color_inactive = text_inactive,\n"
            + "                text_color_locked_active = text_active,\n"
            + "                text_color_locked_inactive = text_inactive,\n"
            + "            },\n"
            + "        },\n"
            + "    })\n"
            + "end\n\n"
            + "return {\n"
            + "    apply_theme = apply_theme\n"
            + "}\n";
    }

    // Hyprland's lua config plugin takes colors as "rgb(RRGGBB)" strings
    // (see noctalia.lua) rather than the "#rrggbb" hex Colors.qml uses.
    function hexToRgbColor(hex) {
        return "rgb(" + hex.replace("#", "").toUpperCase() + ")";
    }

    function writeHyprlandTheme(p) {
        const home = Quickshell.env("HOME");
        heliosLuaFile.path = home + "/.config/hypr/helios.lua";
        heliosLuaFile.setText(root.buildHyprlandTheme(p));
        // Re-sources the whole lua config (hyprland.lua requires this file
        // and calls apply_theme() on load) so the new border colors take
        // effect immediately instead of waiting for the next manual reload.
        hyprctlReloadProc.running = false;
        hyprctlReloadProc.running = true;
    }

    property FileView heliosLuaFile: FileView { printErrors: false; atomicWrites: true }
    property Process hyprctlReloadProc: Process { command: ["hyprctl", "reload"] }
}
