pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// btop
QtObject {
    id: root

    function buildBtopTheme(p) {
        const grad = (key) => "theme[" + key + "_start]=\"" + p.success + "\"\n"
            + "theme[" + key + "_mid]=\"" + p.warning + "\"\n"
            + "theme[" + key + "_end]=\"" + p.danger + "\"\n";
        return "# btop theme generated by Helios\n\n"
            + "theme[main_bg]=\"" + p.background + "\"\n"
            + "theme[main_fg]=\"" + p.text + "\"\n"
            + "theme[title]=\"" + p.accent + "\"\n"
            + "theme[hi_fg]=\"" + p.accent + "\"\n"
            + "theme[selected_bg]=\"" + p.surfaceHigh + "\"\n"
            + "theme[selected_fg]=\"" + p.text + "\"\n"
            + "theme[inactive_fg]=\"" + p.subtext + "\"\n"
            + "theme[proc_misc]=\"" + p.subtext + "\"\n"
            + "theme[cpu_box]=\"" + p.overlay + "\"\n"
            + "theme[mem_box]=\"" + p.overlay + "\"\n"
            + "theme[net_box]=\"" + p.overlay + "\"\n"
            + "theme[proc_box]=\"" + p.overlay + "\"\n"
            + "theme[div_line]=\"" + p.overlay + "\"\n"
            + grad("temp") + grad("cpu") + grad("free") + grad("cached")
            + grad("available") + grad("used") + grad("download") + grad("upload");
    }

    function writeBtopTheme(p) {
        const home = Quickshell.env("HOME");
        btopThemeFile.path = home + "/.config/btop/themes/helios.theme";
        btopThemeFile.setText(root.buildBtopTheme(p));

        btopConfigFile.path = home + "/.config/btop/btop.conf";
        const existing = btopConfigFile.text();
        const text = /^color_theme\s*=.*$/m.test(existing)
            ? existing.replace(/^color_theme\s*=.*$/m, 'color_theme = "helios"')
            : existing.replace(/\s*$/, "") + '\ncolor_theme = "helios"\n';
        btopConfigFile.setText(text);
    }

    property FileView btopThemeFile: FileView { printErrors: false; atomicWrites: true }
    property FileView btopConfigFile: FileView { printErrors: false; atomicWrites: true; preload: true; blockLoading: true }
}
