pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Fuzzel
QtObject {
    id: root

    // fuzzel wants RRGGBBAA with no leading "#".
    function rgba(hex) { return String(hex).replace("#", "").slice(0, 6) + "ff"; }

    function buildFuzzelTheme(p) {
        return "# Generated by Helios (Themes.qml) — do not edit by hand\n\n"
            + "[colors]\n"
            + "background=" + root.rgba(p.background) + "\n"
            + "text=" + root.rgba(p.text) + "\n"
            + "prompt=" + root.rgba(p.subtext) + "\n"
            + "placeholder=" + root.rgba(p.overlay) + "\n"
            + "input=" + root.rgba(p.text) + "\n"
            + "match=" + root.rgba(p.accent) + "\n"
            + "selection=" + root.rgba(p.accent) + "\n"
            + "selection-text=" + root.rgba(p.accentText) + "\n"
            + "selection-match=" + root.rgba(p.accentText) + "\n"
            + "counter=" + root.rgba(p.subtext) + "\n"
            + "border=" + root.rgba(p.accent) + "\n";
    }

    // Puts the include in the main section after any existing includes, so
    // Helios colors win over an earlier theme include.
    function withInclude(existing, includeLine) {
        const lines = (existing || "").split("\n");
        if (lines.some(line => line.trim() === includeLine)) return existing;
        let insertAt = 0;
        for (let i = 0; i < lines.length; i++) {
            const line = lines[i].trim();
            if (/^\[/.test(line) && line !== "[main]") break;
            if (/^include\s*=/.test(line) || line === "[main]") insertAt = i + 1;
        }
        lines.splice(insertAt, 0, includeLine);
        return lines.join("\n");
    }

    function writeFuzzelTheme(p) {
        const home = Quickshell.env("HOME");
        fuzzelThemeFile.path = home + "/.config/fuzzel/themes/helios";
        fuzzelThemeFile.setText(root.buildFuzzelTheme(p));

        fuzzelConfigFile.path = home + "/.config/fuzzel/fuzzel.ini";
        fuzzelConfigFile.setText(root.withInclude(fuzzelConfigFile.text(), "include=" + home + "/.config/fuzzel/themes/helios"));
    }

    property FileView fuzzelThemeFile: FileView { printErrors: false; atomicWrites: true }
    property FileView fuzzelConfigFile: FileView { printErrors: false; atomicWrites: true; preload: true; blockLoading: true }
}
