pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Wofi
QtObject {
    id: root

    function buildWofiCss(p) {
        return "/* Generated by Helios (Themes.qml) — do not edit by hand */\n\n"
            + "window { background-color: " + p.background + "; color: " + p.text + "; }\n"
            + "#input { background-color: " + p.surface + "; color: " + p.text + "; border-color: " + p.overlay + "; }\n"
            + "#outer-box { background-color: " + p.background + "; }\n"
            + "#scroll { background-color: " + p.background + "; }\n"
            + "#entry { background-color: " + p.background + "; color: " + p.text + "; }\n"
            + "#entry:selected, #entry:hover { background-color: " + p.accent + "; color: " + p.accentText + "; }\n"
            + "#text { color: inherit; }\n";
    }

    function writeWofiTheme(p) {
        const home = Quickshell.env("HOME");
        wofiColorsFile.path = home + "/.config/wofi/helios.css";
        wofiColorsFile.setText(root.buildWofiCss(p));

        wofiStyleFile.path = home + "/.config/wofi/style.css";
        const existing = wofiStyleFile.text();
        const importLine = "@import url(\"helios.css\");";
        const text = existing.indexOf(importLine) >= 0
            ? existing
            : importLine + "\n" + (existing || "");
        wofiStyleFile.setText(text);
    }

    property FileView wofiColorsFile: FileView { printErrors: false; atomicWrites: true }
    property FileView wofiStyleFile: FileView { printErrors: false; atomicWrites: true; preload: true; blockLoading: true }
}
