pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Yazi
//
// Schema pulled from yazi's own embedded default theme.toml (`[mgr]`,
// `[tabs]`, `[mode]`, `[status]`, etc. — the pre-0.4 `[manager]`/single
// `[status]` layout is gone). Only the chrome (borders, selection,
// mode indicator, markers) is themed; filetype/icon rules are left
// alone so the user's existing icon colors survive.
QtObject {
    id: root

    function buildYaziTheme(p) {
        const c = (fg, extra) => "{ fg = \"" + fg + "\"" + (extra || "") + " }";
        const cb = (fg, bg, extra) => "{ fg = \"" + fg + "\", bg = \"" + bg + "\"" + (extra || "") + " }";
        return "# Generated by Helios (Themes.qml) — do not edit by hand\n\n"
            + "[mgr]\n"
            + "cwd = " + c(p.accent) + "\n"
            + "find_keyword  = " + c(p.warning, ", bold = true, italic = true") + "\n"
            + "find_position = " + c(p.accent, ", bg = \"reset\", italic = true") + "\n"
            + "symlink_target = { italic = true }\n"
            + "marker_copied   = " + cb(p.success, p.success) + "\n"
            + "marker_cut      = " + cb(p.danger, p.danger) + "\n"
            + "marker_marked   = " + cb(p.accent, p.accent) + "\n"
            + "marker_selected = " + cb(p.warning, p.warning) + "\n"
            + "count_copied   = " + cb(p.accentText, p.success) + "\n"
            + "count_cut      = " + cb(p.accentText, p.danger) + "\n"
            + "count_selected = " + cb(p.accentText, p.warning) + "\n"
            + "border_style  = " + c(p.overlay) + "\n\n"
            + "[tabs]\n"
            + "active   = " + cb(p.accentText, p.accent, ", bold = true") + "\n"
            + "inactive = " + cb(p.subtext, p.surfaceHigh) + "\n\n"
            + "[mode]\n"
            + "normal_main = " + cb(p.accentText, p.accent, ", bold = true") + "\n"
            + "normal_alt  = " + cb(p.accent, p.surfaceHigh) + "\n"
            + "select_main = " + cb(p.accentText, p.warning, ", bold = true") + "\n"
            + "select_alt  = " + cb(p.warning, p.surfaceHigh) + "\n"
            + "unset_main  = " + cb(p.accentText, p.danger, ", bold = true") + "\n"
            + "unset_alt   = " + cb(p.danger, p.surfaceHigh) + "\n\n"
            + "[indicator]\n"
            + "parent  = { reversed = true }\n"
            + "current = { reversed = true }\n"
            + "preview = { underline = true }\n\n"
            + "[status]\n"
            + "perm_sep   = " + c(p.overlay) + "\n"
            + "perm_type  = " + c(p.accent) + "\n"
            + "perm_read  = " + c(p.success) + "\n"
            + "perm_write = " + c(p.warning) + "\n"
            + "perm_exec  = " + c(p.danger) + "\n"
            + "progress_label  = { bold = true }\n"
            + "progress_normal = " + cb(p.success, p.surfaceHigh) + "\n"
            + "progress_error  = " + cb(p.warning, p.danger) + "\n\n"
            + "[which]\n"
            + "border          = " + c(p.accent) + "\n"
            + "cand            = " + c(p.accent) + "\n"
            + "rest            = " + c(p.overlay) + "\n"
            + "desc            = " + c(p.warning) + "\n"
            + "separator_style = " + c(p.overlay) + "\n\n"
            + "[confirm]\n"
            + "border  = " + c(p.accent) + "\n"
            + "title   = " + c(p.accent) + "\n"
            + "btn_yes = { reversed = true }\n\n"
            + "[spot]\n"
            + "border   = " + c(p.accent) + "\n"
            + "title    = " + c(p.accent) + "\n"
            + "tbl_col  = " + c(p.accent) + "\n"
            + "tbl_cell = " + c(p.warning, ", reversed = true") + "\n\n"
            + "[notify]\n"
            + "title_info  = " + c(p.success) + "\n"
            + "title_warn  = " + c(p.warning) + "\n"
            + "title_error = " + c(p.danger) + "\n\n"
            + "[pick]\n"
            + "border = " + c(p.accent) + "\n"
            + "active = " + c(p.accent, ", bold = true") + "\n\n"
            + "[input]\n"
            + "border   = " + c(p.accent) + "\n"
            + "selected = { reversed = true }\n\n"
            + "[cmp]\n"
            + "border = " + c(p.accent) + "\n"
            + "active = { reversed = true }\n\n"
            + "[tasks]\n"
            + "border  = " + c(p.accent) + "\n"
            + "hovered = " + c(p.accent, ", bold = true") + "\n\n"
            + "[help]\n"
            + "border  = " + c(p.accent) + "\n"
            + "chord   = " + c(p.accent) + "\n"
            + "hovered = { reversed = true, bold = true }\n";
    }

    function writeYaziTheme(p) {
        const home = Quickshell.env("HOME");
        yaziThemeFile.path = home + "/.config/yazi/theme.toml";
        yaziThemeFile.setText(root.buildYaziTheme(p));
    }

    property FileView yaziThemeFile: FileView { printErrors: false; atomicWrites: true }
}
