pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Hyprland (border colors, via the hyprland-lua-config plugin)
QtObject {
    id: root

    function buildHyprlandTheme(p) {
        const active = root.hexToRgbColor(p.accent);
        const inactive = root.hexToRgbColor(p.surface);
        const locked = root.hexToRgbColor(p.danger);
        const textOnActive = root.hexToRgbColor(p.accentText);
        const textOnInactive = root.hexToRgbColor(p.text);
        return "-- Generated by Helios (Themes.qml) — do not edit by hand\n\n"
            + "local active = \"" + active + "\"\n"
            + "local inactive = \"" + inactive + "\"\n"
            + "local locked = \"" + locked + "\"\n"
            + "local text_active = \"" + textOnActive + "\"\n"
            + "local text_inactive = \"" + textOnInactive + "\"\n\n"
            + "local function apply_theme()\n"
            + "    hl.config({\n"
            + "        general = {\n"
            + "            col = {\n"
            + "                active_border = active,\n"
            + "                inactive_border = inactive,\n"
            + "            },\n"
            + "        },\n"
            + "        group = {\n"
            + "            col = {\n"
            + "                border_active = active,\n"
            + "                border_inactive = inactive,\n"
            + "                border_locked_active = locked,\n"
            + "                border_locked_inactive = inactive,\n"
            + "            },\n\n"
            + "            groupbar = {\n"
            + "                gradients = true,\n"
            + "                col = {\n"
            + "                    active = active,\n"
            + "                    inactive = inactive,\n"
            + "                    locked_active = locked,\n"
            + "                    locked_inactive = inactive,\n"
            + "                },\n"
            + "                text_color = text_active,\n"
            + "                text_color_inactive = text_inactive,\n"
            + "                text_color_locked_active = text_active,\n"
            + "                text_color_locked_inactive = text_inactive,\n"
            + "            },\n"
            + "        },\n"
            + "    })\n"
            + "end\n\n"
            + "return {\n"
            + "    apply_theme = apply_theme\n"
            + "}\n";
    }

    // Hyprland's lua config plugin takes colors as "rgb(RRGGBB)" strings
    // (see noctalia.lua) rather than the "#rrggbb" hex Colors.qml uses.
    function hexToRgbColor(hex) {
        return "rgb(" + hex.replace("#", "").toUpperCase() + ")";
    }

    function writeHyprlandTheme(p) {
        staleFileRemoveProc.running = false;
        staleFileRemoveProc.running = true;
        const home = Quickshell.env("HOME");
        initLuaFile.path = home + "/.config/hypr/helios/init.lua";
        initLuaFile.setText(root.buildInitLua());
        themeLuaFile.path = home + "/.config/hypr/helios/theme.lua";
        themeLuaFile.setText(root.buildHyprlandTheme(p));
        // Re-sources the whole lua config (hyprland.lua requires this file
        // and calls apply_theme() on load) so the new border colors take
        // effect immediately instead of waiting for the next manual reload.
        hyprctlReloadProc.running = false;
        hyprctlReloadProc.running = true;
    }

    // Requires every helios/*.lua section module (each pcall-wrapped so a
    // section that hasn't been saved yet, and so doesn't exist on disk,
    // fails its own require without blocking the rest) and re-exports
    // apply_theme so hyprland.lua's existing require("helios").apply_theme()
    // call keeps working unchanged against the new directory module.
    function buildInitLua() {
        const sections = ["general", "decoration", "animations", "input",
            "gestures", "group", "misc", "xwayland", "cursor", "render", "debug",
            "ecosystem", "binds", "window_rules", "layer_rules"];
        let body = "-- Generated by Helios (ThemeHyprland.qml) — do not edit by hand\n\n";
        for (const s of sections)
            body += "pcall(function() require(\"helios." + s + "\") end)\n";
        body += "\nreturn require(\"helios.theme\")\n";
        return body;
    }

    property FileView initLuaFile: FileView { printErrors: false; atomicWrites: true }
    property FileView themeLuaFile: FileView { printErrors: false; atomicWrites: true }
    property Process staleFileRemoveProc: Process {
        command: ["sh", "-c", "f=\"$1\"; [ -f \"$f\" ] && [ ! -L \"$f\" ] && rm -f \"$f\"; true", "--", Quickshell.env("HOME") + "/.config/hypr/helios.lua"]
    }
    property Process hyprctlReloadProc: Process { command: ["hyprctl", "reload"] }
}
