pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// WezTerm
QtObject {
    id: root

    function buildWeztermTheme(p) {
        return "-- Generated by Helios (Themes.qml) — do not edit by hand\n\n"
            + "[colors]\n"
            + "foreground = '" + p.text + "'\n"
            + "background = '" + p.background + "'\n"
            + "cursor_bg = '" + p.accent + "'\n"
            + "cursor_fg = '" + p.background + "'\n"
            + "cursor_border = '" + p.accent + "'\n"
            + "selection_fg = '" + p.text + "'\n"
            + "selection_bg = '" + p.surfaceHigh + "'\n"
            + "ansi = ['" + p.surfaceHigh + "', '" + p.danger + "', '" + p.success + "', '" + p.warning
            + "', '" + p.accent + "', '" + p.accent + "', '" + p.accent + "', '" + p.text + "']\n"
            + "brights = ['" + p.overlay + "', '" + p.danger + "', '" + p.success + "', '" + p.warning
            + "', '" + p.accent + "', '" + p.accent + "', '" + p.accent + "', '" + p.text + "']\n\n"
            + "[colors.tab_bar]\n"
            + "background = '" + p.surface + "'\n";
    }

    // Best-effort, like Firefox: wezterm.lua is arbitrary Lua, so this only
    // patches a `config.color_scheme = '...'` assignment if one already
    // exists (the common `wezterm.config_builder()` convention) rather than
    // trying to parse/rewrite the whole file.
    function writeWeztermTheme(p) {
        const home = Quickshell.env("HOME");
        weztermThemeFile.path = home + "/.config/wezterm/colors/helios.toml";
        weztermThemeFile.setText(root.buildWeztermTheme(p));

        weztermConfigFile.path = home + "/.config/wezterm/wezterm.lua";
        const existing = weztermConfigFile.text();
        if (!existing) return;
        const text = /config\.color_scheme\s*=/.test(existing)
            ? existing.replace(/config\.color_scheme\s*=.*/, "config.color_scheme = 'helios'")
            : existing.replace(/\breturn\s+config\b/, "config.color_scheme = 'helios'\n\nreturn config");
        weztermConfigFile.setText(text);
    }

    property FileView weztermThemeFile: FileView { printErrors: false; atomicWrites: true }
    property FileView weztermConfigFile: FileView { printErrors: false; atomicWrites: true; preload: true; blockLoading: true }
}
