pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Alacritty
QtObject {
    id: root

    function buildAlacrittyTheme(p) {
        return "# Generated by Helios (Themes.qml) — do not edit by hand\n\n"
            + "[colors.primary]\n"
            + "background = '" + p.background + "'\n"
            + "foreground = '" + p.text + "'\n\n"
            + "[colors.cursor]\n"
            + "text = '" + p.background + "'\n"
            + "cursor = '" + p.accent + "'\n\n"
            + "[colors.selection]\n"
            + "text = '" + p.text + "'\n"
            + "background = '" + p.surfaceHigh + "'\n\n"
            + "[colors.normal]\n"
            + "black = '" + p.surfaceHigh + "'\n"
            + "red = '" + p.danger + "'\n"
            + "green = '" + p.success + "'\n"
            + "yellow = '" + p.warning + "'\n"
            + "blue = '" + p.accent + "'\n"
            + "magenta = '" + p.accent + "'\n"
            + "cyan = '" + p.accent + "'\n"
            + "white = '" + p.text + "'\n\n"
            + "[colors.bright]\n"
            + "black = '" + p.overlay + "'\n"
            + "red = '" + p.danger + "'\n"
            + "green = '" + p.success + "'\n"
            + "yellow = '" + p.warning + "'\n"
            + "blue = '" + p.accent + "'\n"
            + "magenta = '" + p.accent + "'\n"
            + "cyan = '" + p.accent + "'\n"
            + "white = '" + p.text + "'\n";
    }

    function writeAlacrittyTheme(p) {
        const home = Quickshell.env("HOME");
        alacrittyThemeFile.path = home + "/.config/alacritty/themes/helios.toml";
        alacrittyThemeFile.setText(root.buildAlacrittyTheme(p));

        alacrittyConfigFile.path = home + "/.config/alacritty/alacritty.toml";
        const existing = alacrittyConfigFile.text();
        const importLine = "import = [\"~/.config/alacritty/themes/helios.toml\"]";
        if (/import\s*=\s*\[[^\]]*helios\.toml/.test(existing)) {
            // already imported, nothing to patch
        } else if (/\[general\]/.test(existing)) {
            if (/^\s*import\s*=/m.test(existing)) {
                alacrittyConfigFile.setText(existing.replace(/^\s*import\s*=\s*\[[^\]]*\]/m,
                    (m) => m.slice(0, -1) + ", \"~/.config/alacritty/themes/helios.toml\"]"));
            } else {
                alacrittyConfigFile.setText(existing.replace(/\[general\]/, "[general]\n" + importLine));
            }
        } else {
            alacrittyConfigFile.setText(existing.replace(/\s*$/, "") + "\n\n[general]\n" + importLine + "\n");
        }
    }

    property FileView alacrittyThemeFile: FileView { printErrors: false; atomicWrites: true }
    property FileView alacrittyConfigFile: FileView { printErrors: false; atomicWrites: true; preload: true; blockLoading: true }
}
