pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Fish — a conf.d drop-in, so new shells pick it up without touching
// config.fish. Globals, not universals, so nothing lingers in fish_variables.
QtObject {
    id: root

    function hex(color) { return String(color).replace("#", "").slice(0, 6); }

    function buildFishTheme(p) {
        const c = name => root.hex(p[name]);
        return "# Generated by Helios (Themes.qml) — do not edit by hand\n\n"
            + "set -g fish_color_normal " + c("text") + "\n"
            + "set -g fish_color_command " + c("accent") + "\n"
            + "set -g fish_color_keyword " + c("accent") + "\n"
            + "set -g fish_color_param " + c("text") + "\n"
            + "set -g fish_color_option " + c("subtext") + "\n"
            + "set -g fish_color_quote " + c("success") + "\n"
            + "set -g fish_color_redirection " + c("subtext") + "\n"
            + "set -g fish_color_end " + c("subtext") + "\n"
            + "set -g fish_color_operator " + c("warning") + "\n"
            + "set -g fish_color_escape " + c("warning") + "\n"
            + "set -g fish_color_error " + c("danger") + "\n"
            + "set -g fish_color_comment " + c("overlay") + "\n"
            + "set -g fish_color_autosuggestion " + c("overlay") + "\n"
            + "set -g fish_color_valid_path --underline\n"
            + "set -g fish_color_selection --background=" + c("surfaceHigh") + "\n"
            + "set -g fish_color_search_match --background=" + c("surfaceHigh") + "\n"
            + "set -g fish_pager_color_prefix " + c("accent") + " --bold\n"
            + "set -g fish_pager_color_completion " + c("text") + "\n"
            + "set -g fish_pager_color_description " + c("subtext") + "\n"
            + "set -g fish_pager_color_progress " + c("subtext") + "\n";
    }

    function writeFishTheme(p) {
        fishThemeFile.path = Quickshell.env("HOME") + "/.config/fish/conf.d/helios-colors.fish";
        fishThemeFile.setText(root.buildFishTheme(p));
    }

    property FileView fishThemeFile: FileView { printErrors: false; atomicWrites: true }
}
