pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// tmux
QtObject {
    id: root

    function buildTmuxTheme(p) {
        return "# Generated by Helios (Themes.qml) — do not edit by hand\n\n"
            + "set -g status-style \"bg=" + p.surface + ",fg=" + p.text + "\"\n"
            + "set -g status-left-style \"bg=" + p.accent + ",fg=" + p.accentText + "\"\n"
            + "set -g status-right-style \"bg=" + p.surface + ",fg=" + p.subtext + "\"\n"
            + "set -g window-status-current-style \"bg=" + p.surfaceHigh + ",fg=" + p.text + "\"\n"
            + "set -g window-status-style \"bg=" + p.surface + ",fg=" + p.subtext + "\"\n"
            + "set -g pane-border-style \"fg=" + p.overlay + "\"\n"
            + "set -g pane-active-border-style \"fg=" + p.accent + "\"\n"
            + "set -g message-style \"bg=" + p.surfaceHigh + ",fg=" + p.text + "\"\n"
            + "set -g mode-style \"bg=" + p.accent + ",fg=" + p.accentText + "\"\n";
    }

    function writeTmuxTheme(p) {
        const home = Quickshell.env("HOME");
        tmuxThemeFile.path = home + "/.config/tmux/helios.conf";
        tmuxThemeFile.setText(root.buildTmuxTheme(p));

        tmuxConfigFile.path = home + "/.config/tmux/tmux.conf";
        const existing = tmuxConfigFile.text();
        const sourceLine = "source-file ~/.config/tmux/helios.conf";
        const text = /^\s*source-file\s+~\/\.config\/tmux\/helios\.conf\s*$/m.test(existing)
            ? existing
            : (existing || "").replace(/\s*$/, "") + "\n" + sourceLine + "\n";
        tmuxConfigFile.setText(text);

        // Live-reloads any running tmux server; harmless no-op if none is running.
        tmuxReloadProc.running = false;
        tmuxReloadProc.running = true;
    }

    property FileView tmuxThemeFile: FileView { printErrors: false; atomicWrites: true }
    property FileView tmuxConfigFile: FileView { printErrors: false; atomicWrites: true; preload: true; blockLoading: true }
    property Process tmuxReloadProc: Process { command: ["tmux", "source-file", Quickshell.env("HOME") + "/.config/tmux/tmux.conf"] }
}
